### ISSUE TITLE
number of deaths don't correspond with official day-to-day data

### ISSUE THREAD

**Issue by johanneswilm** [codler/sweden-coronavirus#3]
Hey,
it looks like there is some difference in how you report the "daily deaths" and how the official statistics present them. If I understand the difference right, when on day X Y number of corona deaths are presented, you put it on that date. However, those statistics seem to be from several days earlier and in the official stats they therefore file them under the date that the people actually died.

Did I understand that correctly? If that is the case, given that your site is used by all kinds of world wide sites these days, I think you should consider adding a disclaimer about this as it really has an impact on what the graphs look like.

The official graph [1]:

![FOHM Covid-19](https://user-images.githubusercontent.com/595512/79231790-e4496280-7e66-11ea-8c6b-ef55fb5e764e.png)

Your graph:

![Sverigekarta  Coronavirus  COVID-19  (1)](https://user-images.githubusercontent.com/595512/79231931-1c50a580-7e67-11ea-8221-2a1875fac7db.png)

[1] https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa

**Comment by codler** [comment]
Duplicate #2

**Comment by johanneswilm** [comment]
Sorry, that's not a duplicate. This is  major issue and you are spreading fake news if you don't fix it.

**Comment by johanneswilm** [comment]
Please fix it or take yous tie offline @codler .
